services:
  app:
    image: sagar/student-rest-api:1.0
    ports:
      - "8080:8080"
    networks:
      - s-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlDb:3306/userdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqlDb

  mysqlDb:
    image: mysql:8.4
    environment:
      DATABASE_HOST: docker_mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root

    networks:
      - s-network


networks:
      s-network:
        driver: bridge
