services:

  mysqldb:
    image: mysql:8.0
    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_app

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - springboot-mysql-network

  springboot-app:
    build: .
    container_name: springboot-app

    depends_on:
      - mysqldb

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/student_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    networks:
      - springboot-mysql-network

networks:
  springboot-mysql-network:

volumes:
  mysql_data: